### PR TITLE
add a benchmark using Oleg's delimcc library

### PR DESCRIPTION
**Pull request by gasche**
Delimcc is an implementation of delimited control using a runtime hack
that is not claimed to be efficient. The bytecode implementation is
simpler/faster than the native implementation; on this benchmark,
because control costs dominate, this means that the bytecode program
is simpler/faster than the native program.

(To install, `opam install delimcc`.)

On my machine:

```
$ ocamlfind ocamlc -package delimcc -linkpkg delimcc_nondet.ml -o delimcc_nondet.byte
$ time ocamlrun ./delimcc_nondet.byte 12
14200

real	0m7.053s
user	0m7.026s
sys	0m0.007s

$ ocamlfind ocamlopt -package delimcc -linkpkg delimcc_nondet.ml -o delimcc_nondet.native
$ ./delimcc_nondet.native 12
14200

real	0m9.221s
user	0m9.155s
sys	0m0.007s
```

(in comparison, delim_nondet.ml takes about 6.7 seconds on the same input.)

This delimcc version works well with OCaml 4.04 and 4.05, but not
with the newest version 4.06, which appears to be incompatible
with delimcc due to a runtime change. I reported the issue to Oleg.

### CODE REVIEW

**Comment by jkoppel** [comment]
Wait, delim_nondet.ml is the thermometer continuation one, right? (It's missing dependencies, so I can't tell what it does even though I wrote it.) So thermometer continuations beats delimcc? Wow!

Could you add these build instructions to the repo?

Nice work Gabriel!

**Comment by gasche** [comment]
For delim_nondet, I reused the OCaml code that was lying around, and it does not correspond to your current implementation (there is only one stack instead of three (replay, record, reset)). Your current implementation may perform more bookeeping and be slower. I will refresh delim_nondet to match the corresponding `delim.sml` file.

Of course, it is also easy to build an example where `delimcc` (or SML's call/cc) beat your approach by a large margin, by performing a costly computation before the effect -- which will get replayed each time.

```ocaml
let _ = withNondeterminism (fun () ->
    for i = 0 to 100_000_000 do ignore () done;
    let n = choose [0; 1; 2; 3; 4; 5; 6; 7; 8; 9] in
    [n]
)
```

For this example, your implementation is ten times slower than delimcc -- no surprise. But yes, your approach is surprisingly effective when control time dominates.

**Comment by jkoppel** [comment]
Wow, awesome! This definitely makes the paper stronger.

**Comment by jkoppel** [comment]
Add a README with how to run and I'll merge. It sounds like you changed delim_nondet; if that is the case, then add that too.

**Comment by jkoppel** [comment]
Ah; I see your other PR now with delim_nondet.

**Comment by gasche** [comment]
I pushed a Makefile in `ocaml`; `make all` builds the benchmarks without third-party dependencies, and `make delimcc` builds the delimcc benchmark. I also changed your `run_benchmark_time.rb` script to match the behavior of `run_benchmark.rb` (it runs on inputs [4; 12] and outputs milliseconds rather than seconds), so that 

```
ruby run_benchmark.rb replay_nondet.sml
make -C ocaml
ruby run_benchmark_time.rb ./ocaml/replay_nondet.native
```

behaves as expected.

**Pull request merged**
